
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  archives: /archives
  tags: /tags
  #categories: /categories
  search: /search
  about: /about 
  rss: /atom.xml

title: Xcoding

# Miscelaneous
favicon: /image/favicon.ico

permalink: :title/


# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- /css/pure-min.css
- /css/xoxo.css

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js


# switch
show_excerpt: true
show_date: true
#footer
index_page: http://xcoding.tech/ 
main_site: http://xcoding.tech/
github: https://github.com/ubuntuvim
