
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  search: /search
  tags: /tags
  archives: /archives
  about: /about
  # rss: /atom.xml

search:
  path: search.xml
  field: post
  content: true

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

# 网站标题
#title: 

# Miscelaneous
favicon: /image/favicon.ico

permalink: :title/


# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- /css/pure-min.css
- /css/xoxo.css

# scripts loaded in the end of the body
scripts:
- /js/zepto.min.js
#- /js/xoxo.js
# - /js/gitment.browser.js


# switch
show_excerpt: true
show_date: true
# show_excerpt: true
# excerpt: true


#footer
index_page: http://xcoding.tech/
main_site: http://xcoding.tech/
github: https://github.com/ubuntuvim

# mermaid chart
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  version: "7.1.2" # default v7.1.2
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    #startOnload: true  // default true
    external_link: false    


plugins:
  gitalk:
    clientID: 48b3df0bf4ba1743e0a3
    clientSecret: 4cf1e76de9e18b9ad0def477c36ab22059b152c8
    repo: ubuntuvim.github.io
    owner: ubuntuvim
    admin: 
      - ubuntuvim
    distractionFreeMode: false
